### ISSUE TITLE
Unable to write "undefined" file

### ISSUE THREAD

**Issue by subarroca** [werk85/grunt-ng-constant#31]
Hi,

I followed a tutorial @ http://mindthecode.com/how-to-use-environment-variables-in-your-angular-application/

My grunt config looks like: 

``` js
grunt.initConfig({
  ngconstant: {
      options: {
        space: '  ',
      },
      // Environment targets
      dev: [{
        dest: '<%= yeoman.app %>/scripts/config.js',
        name: 'config',
        wrap: '"use strict";\n\n <%= __ngModule %>',
        constants: {
          ENV: {
            name: 'dev',
            apiurl: 'http://localhost:8000'
          }
        }
      }],
      prod: [{
        dest: '<%= yeoman.dist %>/scripts/config.js',
        name: 'config',
        wrap: '"use strict";\n\n <%= __ngModule %>',
        constants: {
          ENV: {
            name: 'prod',
            apiUrl: '...'
          }
        }
      }]
    }

...
```

and

``` js
grunt.registerTask('serve', function(target) {
    if (target === 'dist') {
      return grunt.task.run(['build', 'connect:dist:keepalive']);
    }

    grunt.task.run([
      'clean:server',
      'ngconstant:dev',
      'bower-install',
      'concurrent:server',
      'autoprefixer',
      'connect:livereload',
      'watch'
    ]);
  });
```

What I get once I run _grunt serve_ is:

Running "ngconstant:dev" (ngconstant) task
Creating module undefined at undefined...Warning: Unable to write "undefined" file (Error code: undefined). Use --force to continue.

The task is correctly detected but I guess the problem is with generated content.

Any hint?

**Comment by sunny200745** [comment]
Hi ,
I am facing a problem with ngconstant , while running the "grunt ngconstant" it gives me the following error "Running tasks: ngconstant : Running "ngconstant" task
Warning: Task "undefined" not found. Used --force, continuing."

My ngconstant task looks like :
ngconstant: {
      options: {
        name: 'mobility.config',
        dest: '<%= yeoman.app %>/modules/config.js',
        wrap: '\'use strict\';\n\n {%= __ngModule %}',
        constants: {
          API_ENDPOINT: '<%= grunt.config("api_endpoint") %>'        
        }
      },
      build: {
      }
    }

Please help .

thanks
