### ISSUE TITLE
possible to add multiple ngconstants to a task?

### ISSUE THREAD

**Issue by armyofda12mnkeys** [werk85/grunt-ng-constant#51]
So it might be best to demonstrate my example:

I need to setup a dev/qa/prod environments for my angular project so I setup constants like ngconstant:DEV, which then pulls the correct DEV webservice url and points to the DEV db in my app controllers and also displays a debug toolbar in my template.

But I have two kinds of DEV environments, one when testing locally and one for the DEV box build.
When I am testing locally i'd like to add another attribute like so for my 'server' task:

      'ngconstant:DEV',        //for pointing to correct dev urls/db's/debug windows
      'ngconstant:LOCALHOST_DEBUGGING', //boolean for local debugging as I may do certain things only locally like clear cache via $templateCache, or show certain things in my app

The 'build-dev' task will just have:
      'ngconstant:DEV',        

But in the former case for the 'server' task, the config file only has the latter constant instead of both.

Here is my config:
```
ngconstant: {
      options: {
        name: 'EnvConfig',
        space: ' ',
        wrap: true,
        dest: '.tmp/scripts/config.js'
      },
      // Environment targets
      LOCALHOST_DEBUGGING: {
        constants: {
          LOCALHOST_DEBUGGING: true
        }
      },
      DEV: {
        constants: {
          ENV: {
            id: 'DEV',
            name: 'development',
            debug_toolbar: true,
            ws_url: 'dev.example.com'
          }
        }
      },
      // Environment targets
      QA: {
        constants: {
          ENV: {
            id: 'QA',
            name: 'qa',
            debug_toolbar: true,
            ws_url: 'qa.example.com'
          }
        }
      },
      /* I might needs a local environment so uses .tmp but others use final directory ? */
      PROD: {
        constants: {
          ENV: {
            id: 'PROD',
            name: 'production',
            debug_toolbar: false,
            ws_url: 'prod.example.com'
          }
        }
      }
    },
```

and grunt task:

```
grunt.registerTask('serve', 'Compile then start a connect web server', function (target) {
...

    grunt.task.run([
      'clean:server',
      'ngconstant:QA',      
      'ngconstant:LOCALHOST_DEBUGGING', 
..
});
```

I tried also alternatively 'merging' the variables but that didnt work either (for example using the same ENV obj but having another property and hoping the ng-constant merges it). That seemed less likely to work than above though (although that would be pretty cool to get working, then i dont need to import multiple ngconstants in my controller and just import 1 constant ENV).
```
  LOCALHOST_DEBUGGING: {
        constants: {
        ENV: {
           extra-merged-param: 'doesnt work either'
        }
      },
```

I guess I could setup a totally separate set of properties but seems like maybe we can make ngconstant just do multiple variables, instead of this:
      'ngconstant:DEV',
      'ngconstant:DEV_and_LOCAL',      //has same props as ngconstant:DEV, +1 more property for stating im debugging locally
      'ngconstant:QA',
      'ngconstant:QA_and_LOCAL',
      'ngconstant:STAGING',
      'ngconstant:STAGING_and_LOCAL',
      'ngconstant:PROD',

**Comment by armyofda12mnkeys** [comment]
Im guessing that based on the main page I could create a separate entire module like so?
```
      LOCALHOST_DEBUGGING: {
        options: {
          name: 'LocalConfig',
          dest: '.tmp/scripts/local.js'
        },
```
But is there a way to just have it under 1 module so can just import all my possibly env vars under ENV.

**Comment by mlegenhausen** [comment]
You should use only one file. Multiple file support is only possible when using multiple targets, which is a little bit more complicated (as you find out).

I think you should use the top level options and then override your `LOCALHOST_DEBUGGING` var.

```js
options: {
  ...
  constants: {
    LOCALHOST_DEBUGGING: false
  }
},
DEV: {
  constants: {
    LOCALHOST_DEBUGGING: true,
    ENV: { ... }
  }
}
```

**Comment by armyofda12mnkeys** [comment]
Thanks @mlegenhausen, that'll work out for me :)
