### ISSUE TITLE
will the config file be built in main js file or will be inserted in index.html file?

### ISSUE THREAD

**Issue by abbymrs** [werk85/grunt-ng-constant#57]
Hi,

I would like to know will the config file be built in main js file or will be inserted in index.html file?
Hope to receive your kindly reply soon.
Thanks a lot!

**Comment by mlegenhausen** [comment]
This plugin does not insert any data in already existing files. When you try out my example configuration in the "Overview" section described in the `README` of this project you will see that a separate file with the name `config.js` will be generated. This file contains a new `angular.module`. You load this file by referencing it via a script tag in your `index.html` file and add the module name (in this case `config`) in your app module e. g. `angular.module('app', ['config'])`. I hope this helps.

**Comment by abbymrs** [comment]
@mlegenhausen If the config json file is changed, will it be rebuilt?

**Comment by abbymrs** [comment]
What I need is when change the config file, the page will response immediately, like show/hide some pages.

**Comment by mlegenhausen** [comment]
This is out of scope of this task. You need to configure your watch task appropriately. See https://github.com/gruntjs/grunt-contrib-watch for further informations on this topic.

**Comment by abbymrs** [comment]
ok, thanks!
